#!/usr/bin/perl -w

use 5.10.0;

=for TODO

Add --version

Add "test" action

Add "clean" action

Let it copy over static stuff.

=cut

use strict;
use warnings;

use Carp::Always;
use App::Podium;

MAIN: {
    my $config = App::Podium::get_config();

    my @commands = @ARGV;

    for my $command ( @commands ) {
        given ( $command ) {
            when ('build') { App::Podium::command_build( $config ) }
            when ('clean') { App::Podium::command_clean( $config ) }
            default { say qq{Unknown command "$command"} }
        }
    }
}

=head1 AUTHOR

Andy Lester, C<< <andy at petdance.com> >>

=head1 BUGS

Please report any bugs or feature requests to the issues list at
Github: L<http://github.com/petdance/ack/issues>.  I will be notified,
and then you'll automatically be notified of progress on your bug
as I make changes.

=head1 SUPPORT

=over 4

=item * Bugs

L<http://github.com/petdance/ack/issues>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/podium>

=item * CPAN Ratings

L<http://cpanratings.perl.org/d/podium>

=item * Search CPAN

L<http://search.cpan.org/dist/podium/>

=back

=head1 ACKNOWLEDGEMENTS

I would love to populate this section.  Please send me your contributions.

=head1 COPYRIGHT & LICENSE

Copyright 2010 Andy Lester

This program is free software; you can redistribute it and/or modify
it under the terms of either:

=over 4

=item * the GNU General Public License as published by the Free
Software Foundation; either version 1, or (at your option) any later
version, or

=item * the Artistic License version 2.0.

=back

=cut
